"""GENERADO — imagen dorada post-tutorial para el tutorial-skip (v0.2).

Bytes de RAM 0x021602A8..+0x4F4 capturados de un LOAD real post-intro en el
hub (exp186/195). El cliente los escribe ahí durante los menús de la primera
sesión; el parche de ROM redirige "New Game" al handler de LOAD, que entra a
la escena usando este bloque canónico + descriptor (hub jugable, sin intro).
Estado seed-independiente: el modelo del YAML se aplica ENCIMA por el cliente.
"""

import base64

GOLDEN_IMAGE_ADDR = 0x021602A8
GOLDEN_IMAGE_B64 = (
    "ugUBAAAAAABGEBF6AAAAgAAAGAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAQAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAACCAAAAAAA"
    "AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZAAAAAAAAAAIBwAAAAAAAOgDAAAAAAAA"
    "ZAAAAAAAAACSAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAA"
    "AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZAAAAAAAAAAIBwAAAAAAAOgDAAAAAAAA"
    "ZAAAAAAAAAAAAAAAACABAP9fAQBGEBF6AiABYQIBAAAUAAAAAQAQAAAAAAAAAAAAAAABAQIDBAUG"
    "BwgICQkKCwAAAAAAAAAAAAD/////////////////////AwAAAAAAQACAACAAEAAACAABAgAAAgAE"
    "AQAAAAEAAKANAABwBAABEAFhARABYQQBAAAAAAAAAAAQAAAAAAAAAAAAAAABAQIDBAUGBwgICQkK"
    "CwAAAAAAAAAAAAD/////////////////////AwAAAAAAQACAACAAEAAACAABAgAAAgAEAQAAAAEA"
    "AAAAAAEAAAAwzQAAAAAAAAALABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAQAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAA="
)
GOLDEN_IMAGE = base64.b64decode(GOLDEN_IMAGE_B64)
assert len(GOLDEN_IMAGE) == 0x4F4
