"""Universal Tracker: auto-tab and player position icon.

The client writes the key `mmzx_pos_<slot>` = [subarea, x, y] (room px;
rate-limited) to the server's data storage.
UT watches that key (tracker_world.map_page_setting_key /
location_setting_key) and calls these functions with the value:
  - map_page_index(data) -> index of the current ROOM's map in maps.json
    (per-room map = "zoom"), or 0 if unknown.
  - location_icon_coords(index, data) -> (x, y, icon) in pixels of map
    `index` (room map or area map of that room), or None to hide it.
The transforms come from tracker_meta.py (generated by
tools/gen_tracker_pack.py).
"""

from .tracker_meta import ROOMS, SUB_TO_ROOM, OVERALL_MAP, OVERALL_POINTS, OVERALL_ROOM_POINTS
from .data import HUB_FLOOR_Y

PLAYER_ICON = "images/player.png"
HUB_SUB = 70


def _hub_area(y: int):
    """Hub floor (player y) -> area letter (M before N)."""
    best = None
    for letter, fy in HUB_FLOOR_Y.items():
        d = abs(y - (fy - 17))
        if d <= 96 and (best is None or d < best[0] or (d == best[0] and letter < best[1])):
            best = (d, letter)
    return best[1] if best else None


def _parse(data):
    try:
        sub, x, y = int(data[0]), int(data[1]), int(data[2])
    except (TypeError, ValueError, IndexError, KeyError):
        return None
    return sub, x, y


def map_page_index(data) -> int:
    p = _parse(data)
    if p is None:
        return 0
    if p[0] == HUB_SUB and OVERALL_MAP is not None:
        return int(OVERALL_MAP)          # in the hub: overall map
    info = ROOMS.get(SUB_TO_ROOM.get(p[0], ""))
    if info and info.get("room_map") is not None:
        return int(info["room_map"])
    return 0


def location_icon_coords(index: int, data):
    p = _parse(data)
    if p is None:
        return None
    if index == OVERALL_MAP and OVERALL_MAP is not None:
        # overall map: icon over the box of the current room; in the hub,
        # over the badge of the area of the floor the player is on
        if p[0] == HUB_SUB:
            pt = OVERALL_POINTS.get(_hub_area(p[2]) or "")
        else:
            room = SUB_TO_ROOM.get(p[0], "")
            pt = OVERALL_ROOM_POINTS.get(room) or OVERALL_POINTS.get(room[:1].upper() if room else "")
        return (int(pt[0]), int(pt[1]), PLAYER_ICON) if pt else None
    info = ROOMS.get(SUB_TO_ROOM.get(p[0], ""))
    if not info:
        return None
    if index == info.get("room_map") and info.get("room_xf"):
        ox, oy, sc = info["room_xf"]
    elif index == info.get("area_map") and info.get("area_xf"):
        ox, oy, sc = info["area_xf"]
    else:
        return None
    return int(ox + p[1] * sc), int(oy + p[2] * sc), PLAYER_ICON
